version: '3'

services:
    teachteam-mysql-db:
        image: mysql:8.0
        container_name: mysql_container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: rayan
            MYSQL_PASSWORD: rayan
            MYSQL_ROOT_HOST: '%' #means the default localhost 